version: '3.7'

x-base: &base
  image: robotology/webgui:default
  build:
    dockerfile: Dockerfile
    context: .
    args:
      username: user1
      uid: 1000
      gid: 1000
  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/home/user1/.Xauthority
    - QT_X11_NO_MITSHM=1
    - DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user1/1000/bus
    - XDG_RUNTIME_DIR=/run/user1/1000
    - YARP_COLORED_OUTPUT=1
    - YARP_NAMESPACE=/root
    - ROS_HOSTNAME=localhost
    - ROS_MASTER_URI=http://localhost:11311
    - YARP_PORTNUMBER_grabber=20000
    - PYTHONPATH=${PYTHONPATH}:/home/user1/yarp/build/lib/python3/
  volumes:
    - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    - "${XAUTHORITY}:/home/user1/.Xauthority:rw"
    - "${XDG_RUNTIME_DIR}/yarp:/run/user1/1000/yarp"
    - "${XDG_RUNTIME_DIR}/dconf:/run/user1/1000/dconf"
    - "${XDG_RUNTIME_DIR}/bus:/run/user1/1000/bus"
    - "${HOME}/.config/yarp:/home/user1/.config/yarp:rw"
    - "${HOME}/.local/share/yarp:/home/user1/.local/share/yarp:rw"
    - "${HOME}/.gitconfig:/home/user1/.gitconfig"
    # - ros1-volume:/home/user1/.ros
  # network_mode: host
  # ipc: host
  pid: host
  security_opt:
    - apparmor:unconfined

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.5
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker --web --docker --docker.watch --docker.domain=localhost --logLevel=DEBUG
      - --entrypoints.web-secure.address=:443 
      - --providers.docker=true
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      - "8080:8080"
      # # The Web UI (enabled by --api.insecure=true)
      - "20000:20000"
      # - "30000:30000"
      - "16001:16001"
    volumes:
      # So that Traefik can listen to the Docker events
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config:/etc/traefik"
      - "./certificates:/certificates"

  webgui:
    <<: *base
    container_name: webgui
    command: bash -c "sleep 5;cd /home/user1/yarp-web-teleop; YARP_PORTNUMBER_click=30000 python3 server.py --map_port 20000 --camera_port 20000 --camera_host webgui.docker --click_port /click --no_ssl"
    # command: terminator --no-dbus
    labels:
      - "traefik.enable=true"
      # set traefik to enable dns and tls, together with input and output port
      - "traefik.http.routers.webgui.rule=Host(`webgui.docker`) || Host(`webgui.docker.localhost`)"
      - "traefik.http.routers.webgui.entrypoints=webgui"
      - "traefik.http.routers.webgui.tls=true"
      - "traefik.http.routers.webgui.service=webgui"
      - "traefik.http.services.webgui.loadbalancer.server.port=16001"
      - "traefik.tcp.routers.websocket.rule=HostSNI(`webgui.docker`) || HostSNI(`webgui.docker.localhost`)"
      - "traefik.tcp.routers.websocket.entrypoints=webgui"
      - "traefik.tcp.routers.websocket.tls=true"
      - "traefik.tcp.routers.websocket.service=websocket"
      - "traefik.tcp.services.websocket.loadbalancer.server.port=16001"
      # set the network
      - "traefik.docker.network=traefik_default"
    depends_on:
      - reverse-proxy
      - fakeframegrabber



  fakeframegrabber:
    <<: *base
    container_name: fakeframegrabber
    # FIXME sleep
    command: sh -c "sleep 5; yarp namespace $${YARP_NAMESPACE}; YARP_PORTNUMBER_grabber=20000 yarpdev --device fakeFrameGrabber"
    labels:
      - "traefik.enable=true"
      # set traefik to enable dns and tls, together with input and output port
      - "traefik.http.routers.fakeframegrabber.rule= Host(`webgui.docker`) || Host(`webgui.docker.localhost`)"
      - "traefik.http.routers.fakeframegrabber.entrypoints=mjpegsecure"
      - "traefik.http.routers.fakeframegrabber.tls=true"
      - "traefik.http.services.fakeframegrabber.loadbalancer.server.port=20000"
      # set the network
      - "traefik.docker.network=traefik_default"
      # authentication
      - "traefik.http.routers.fakeframegrabber.middlewares=fakeframegrabberauth"
      - "traefik.http.middlewares.fakeframegrabberauth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.fakeframegrabberauth.forwardauth.address=https://webgui.docker:16001/auth"
      - "traefik.http.middlewares.fakeframegrabberauth.forwardauth.tls.insecureSkipVerify=true"

    depends_on:
      - reverse-proxy
